# Generated by Django 5.0.6 on 2024-06-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('emp_code', models.CharField(max_length=50)),
                ('java', models.CharField(max_length=50)),
                ('cplusplus', models.CharField(max_length=50)),
                ('csharp', models.CharField(max_length=50)),
                ('selenium', models.CharField(max_length=50)),
                ('python', models.CharField(max_length=50)),
                ('powerbi', models.CharField(max_length=50)),
                ('azuredevops', models.CharField(max_length=50)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epirocapp.courses')),
            ],
        ),
    ]
